#!/bin/bash

# Help
Help() {
    echo "iem <command>

Usage:

iem -s <foo>    set the source path
iem -t <foo>    set the target path
iem -h          display usage info for all commands
"
}

# set default values
SOURCE_PATH=/storage/0000-0000
TARGET_PATH=~/storage/pictures/sony

while getopts :s:t:h: option; do
    case $option in
        s) # source path
            SOURCE_PATH=$OPTARG;;
        t) # target path
            TARGET_PATH=$OPTARG;;
        h) # display Help
            Help
            exit;;
        \?) # Invalid option
            echo "unknown command: \"$OPTARG\"

To see a list of supported iem commands, run:
  iem -h"
            exit;;
    esac
done

echo "SOURCE: $SOURCE_PATH"
echo "TARGET: $TARGET_PATH"

import_files() {
    DIR_PATH=$1
    EXT=$2

    files=$(ls $SOURCE_PATH/$DIR_PATH/*/*.$EXT)
    i=1
    max=$(echo $files | wc -w)

    maxl=$(($(echo $max | wc -c)-1))
    for filename in $files; do
        created=$(date -r $filename "+%Y-%m-%d")

        # check if date directory exist
        if [ ! -d $TARGET_PATH/$created/$EXT ]; then
            mkdir -p $TARGET_PATH/$created/$EXT
            printf "\e[36m$TARGET_PATH/$created/$EXT\e[0m directory has been created\n"
        fi

        file=(${filename//\// })

        # check if file exist and copy
        if [ ! -f $TARGET_PATH/$created/$EXT/${file[4]} ]; then
            cp -p $filename $TARGET_PATH/$created/$EXT/${file[4]}
            printf "[%0${maxl}d/$max] \e[32m${file[4]}\e[0m has been created\n" $i
        fi
        i=$((i+1))
    done
}

import_files DCIM JPG
import_files DCIM ARW
import_files PRIVATE/M4ROOT MP4

